# Generated by Django 2.1.2 on 2018-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='s_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
