# Generated by Django 2.1.2 on 2018-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20181113_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='testing', max_length=10),
            preserve_default=False,
        ),
    ]
