# Generated by Django 2.1.2 on 2018-11-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='summary',
        ),
    ]
